version: '3'

services:
  web:
    build: ./
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ~/Desktop/montymobile/:/montymobile/
    environment:
      DJANGO_DEBUG: 1
      DJANGO_READ_DOT_ENV_FILE: 1
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: montymobile_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: montymobile_user
      POSTGRES_PASSWORD: montymobile_password
    volumes:
      - ~/Desktop/psql/:/psql/

  keycloakdb:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:17.0.0
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password # make sure without this line kaycloak will need more conf like add user from sh
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_LOGLEVEL: DEBUG
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_DISCOVERY_PROPERTIES: datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=500,initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - keycloakdb

volumes:
  postgres_data:
  montymobile: